version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: "mysql"
    hostname: mysql
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
    ports:
    - 13306:3306
  php:
    build: ./php
    container_name: "php"
    ports:
    - "1100:80"
    - "1433:433"
    volumes:
    - ./html:/var/www/html
